### PR TITLE
allow accessKeyId & secretAccessKey

### PR DESCRIPTION
**Pull request by yeahoffline**
allow accessKeyId as key and secretAccessKey as secret in opts (like
the official AWSJavaScriptSDK)

### CODE REVIEW

**Comment by jergason** [comment]
Is this just aliasing the names of the options?

**Comment by yeahoffline** [comment]
yes

**Comment by jergason** [comment]
This is a good idea. The README.md should be updated as well to reflect the new options. Once that is done I'm happy to merge this in.

**Comment by yeahoffline** [comment]
done! ty!

**Comment by jergason** [comment]
Thanks for your help on this! Just published a new version to npm with this change applied.

**Comment by yeahoffline** [comment]
ty

**Pull request merged**
